### ISSUE TITLE
Theos updating failing! 

### ISSUE THREAD

**Issue by Dershowitz011** [theos/theos#156] opened 2016-04-28 19:52 UTC
`make update-theos` returning with
Entering 'vendor/include'
fatal: Not a git repository
fatal: Not a git repository
Unable to find current revision in submodule path 'include'
fatal: Not a git repository

**Comment by Dershowitz011** [comment] 2016-04-28 20:14
Update: Doing so
In almost all situations, /var and /opt will not be writable. If this is the case, it is advised that you do not add sudo onto the git clone command unless you have a particular reason to. Clone it to a location you have write access to such as your home directory, then move it as root:

`$ sudo mv theos /opt/theos`

will give the error while updating these using `make update-thees`. Using sudo directly in the /opt directory will clone it fine and update fine too.

**Comment by ahyattdev** [comment] 2016-04-28 23:01
This is a known issue. See #144. 

The problem is git doesn't use relative paths for submodules.

**Comment by kirb** [comment] 2016-04-29 00:03
Closing as a duplicate.

**Closed by kirb** 2016-04-29 00:03 UTC
