### ISSUE TITLE
Theos On Linux os/log

### ISSUE THREAD

**Issue by JakeAi** [theos/theos#300] opened 2018-03-16 19:43 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Run theos on linux
2. Include this in makefile 
```
TARGET = iphone:clang:10.3
include $(THEOS)/makefiles/common.mk
```
Include this in Tweak.xm
```
#import <ChatKit/ChatKit-Structs.h>
#import <libobjc.A.dylib/CKAppInstallationWatcherObserver.h>
```
3. make do

What happens?
-------------
```
/home/jake/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/log.h:17:2: error: using os/log.h requires Xcode 8 or later
#error using os/log.h requires Xcode 8 or later
 ^
In file included from <built-in>:1:
In file included from /home/jake/theos/Prefix.pch:32:
/home/jake/theos/vendor/include/_Prefix/HBLog.h:2:10: fatal error: could not build module 'os'
        #import <os/log.h>
         ~~~~~~~^
2 errors generated.
```

What were you expecting to happen?
----------------------------------
For it to compile?

Any logs, error output, etc?
----------------------------
```
/home/jake/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/log.h:17:2: error: using os/log.h requires Xcode 8 or later
#error using os/log.h requires Xcode 8 or later
 ^
In file included from <built-in>:1:
In file included from /home/jake/theos/Prefix.pch:32:
/home/jake/theos/vendor/include/_Prefix/HBLog.h:2:10: fatal error: could not build module 'os'
        #import <os/log.h>
         ~~~~~~~^
2 errors generated.
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu

**Toolchain Version:** Coolstars

**SDK Version:** 10.3

**Comment by kirb** [comment] 2018-04-15 02:14
Closing as duplicate of #305.

**Closed by kirb** 2018-04-15 02:14 UTC
