### ISSUE TITLE
CocoaPods fails to build with Theos xcodeproj

### ISSUE THREAD

**Issue by absidue** [theos/theos#531] opened 2020-07-05 12:55 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
_I wasn't able to replicate the issue locally, it only seems to occur in our CI environments_

**Steps to reproduce locally**
1. Update theos to a version after the next branch was merged.
2. Clone Zebra and it's submodules (using `--depth=1` ensures that you don't clone multiple GBs of data _only_ ~240MBs):
`git clone --depth=1 --recursive https://github.com/wstyres/Zebra.git`
3. `cd zebra`
4. `make package`

**Reproduce in GitHub Actions**
Fork https://github.com/wstyres/Zebra or push your cloned copy to GitHub. That should automatically trigger the build on the master branch. Any changes made on the master or 1.2 branch will be automatically built by GitHub Actions.

**Reproduce in Travis CI**
1. Fork https://github.com/wstyres/Zebra
2. Make an insignificant change to any of the files.
2. Create a pull request to https://github.com/wstyres/Zebra.
Any pull request made to Zebra triggers the Travis CI build.

**CI configuration**
- GitHub Actions: `.github/workflows/build.yml`
- Travis CI: `.travis.yml`

What happens?
-------------
The `xcodebuild` step fails due to a cyclic dependency error when building the XPC module, where the XPC module includes a class which in turn includes the XPC module. These errors started popping up after the changes from the next branch where merged into the master branch of theos. The app is built by xcode through the xcodebuild command.

Below are the error messages extracted from the build log.
```
❌  /Applications/Xcode-11.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/os/object.h:25:10: cyclic dependency in module 'XPC': XPC -> os_object -> XPC

#include <Availability.h>
         ^

❌  /Applications/Xcode-11.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/dispatch/dispatch.h:25:10: cyclic dependency in module 'XPC': XPC -> Dispatch -> XPC

#include <Availability.h>
 ~~~~~~~~^

❌  /Applications/Xcode-11.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sqlite3.h:88:12: could not build module 'XPC'

#  include <Availability.h>
         ^
```

What were you expecting to happen?
----------------------------------
Theos not to intervene with the app build performed by `xcodebuild` and the build to complete successfully.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

GitHub Actions build log:
Pretty (need to be logged in to GitHub to view): https://github.com/wstyres/Zebra/runs/813123789
Raw: https://gist.github.com/absidue/5d30027c998e9404a0d01ff81830822f

Travis CI build log:
Pretty: https://travis-ci.com/github/wstyres/Zebra/jobs/354655033
Raw: https://api.travis-ci.com/v3/job/354655033/log.txt

Any other comments?
-------------------
Downgrading theos to commit 8771215 (the one before the next branch was merged) resolves the issue.

What versions of software are you using?
----------------------------------------
**Operating System:**
- macOS 10.15.5 (GitHub actions)
- macOS 10.14.6 (Travis CI)

**Toolchain Version:**
- Xcode: 11.5 (GitHub actions)
- Xcode: 11.2.1 (Travis CI)

**SDK Version:** …
- iOS 13.2 (iPhoneOS13.5)
- iOS 13.2 (iPhoneOS13.2)

**VM Setup**:
- GitHub Actions: https://github.com/actions/virtual-environments/blob/15c14c65f0e07a6664d6eb9624bb8827d2576b73/images/macos/macos-10.15-Readme.md
- Travis CI: https://docs.travis-ci.com/user/reference/osx/

**Comment by kabiroberai** [comment] 2020-07-05 13:29
Could you please provide the output of `make clean all messages=yes` on both the latest Theos commit as well as the last commit where it worked?

**Comment by absidue** [comment] 2020-07-05 13:58
Latest commit: https://github.com/absidue/Zebra/runs/838759185
Latest working commit: https://github.com/absidue/Zebra/runs/838769772

**Comment by kabiroberai** [comment] 2020-07-22 22:02
Would it be possible for you to try switching to Theos' `xcodeproj` target type? That's the official way to build Xcode projects with Theos, and it might help resolve this issue since it makes a few Theos-specific changes such as modifying the Derived Data directory location. Check out [NewTerm](https://github.com/hbang/NewTerm/blob/master/Makefile) and [Sileo](https://github.com/Sileo/Sileo/blob/master/Makefile)'s Makefiles to see how it's used.

**Comment by kabiroberai** [comment] 2020-07-22 22:08
This also makes `ipa` packaging easier; it might be as simple as setting `PACKAGE_FORMAT = ipa` for you. You can also do it manually. This is what I do in Supercharge:
```make
ifeq ($(JAILED),1)
internal-package::
	$(ECHO_NOTHING)mv $(THEOS_STAGING_DIR)/Applications $(THEOS_STAGING_DIR)/Payload$(ECHO_END)
	$(ECHO_NOTHING)cd $(THEOS_STAGING_DIR) && zip -yqr9 $(THEOS_PROJECT_DIR)/$(THEOS_PACKAGE_DIR)/Supercharge.ipa Payload/$(ECHO_END)

after-package:: __THEOS_LAST_PACKAGE_FILENAME = $(THEOS_PACKAGE_DIR)/Supercharge.ipa
endif
```

**Comment by absidue** [comment] 2020-07-25 21:08
> Would it be possible for you to try switching to Theos' `xcodeproj` target type? That's the official way to build Xcode projects with Theos, and it might help resolve this issue since it makes a few Theos-specific changes such as modifying the Derived Data directory location. Check out [NewTerm](https://github.com/hbang/NewTerm/blob/master/Makefile) and [Sileo](https://github.com/Sileo/Sileo/blob/master/Makefile)'s Makefiles to see how it's used.

As suggested I have tried to migrate Zebra to the xcodeproj target type. The build is now failing with `could not build module 'LNPopupController'` or `could not build module 'SDWebImage'`. From my testing these errors seem to occur due to theos passing a custom derived data directory to xcodebuild. If I remove the `-derivedDataPath $(THEOS_OBJ_DIR)` parameter from the xcodebuild call in theos, the build passes without any errors. ([see line 50 in `$THEOS/makefiles/instance/xcodeproj.mk`](https://github.com/theos/theos/blob/master/makefiles/instance/xcodeproj.mk#L50))

I would be very grateful if you could review the changes I have done in [commit](https://github.com/absidue/Zebra/commit/a0dd2f90493dba8d7aade3134c1e5b0f7fd9b385) `a0dd2f9` in https://github.com/absidue/Zebra and see if you can spot anything wrong. Other builds such as Sileo work fine on my machine, so my guess is that the dependencies are configured incorrectly although I wasn't able to find anything wrong.

Thanks for your help so far :).

**Comment by wstyres** [comment] 2020-08-18 20:52
@kabiroberai We've switched to theos' new xcodeproj makefiles (https://github.com/wstyres/Zebra/blob/carthage/Makefile) and the issue still occurs with using GitHub Actions.

**Comment by absidue** [comment] 2020-08-18 20:59
We resolved the not being able to build the dependencies issue by switching to carthage.

**Comment by kabiroberai** [comment] 2020-08-18 21:00
Apologies for the late response; I seem to have missed your last message @absidue. Has the issue been resolved? If not, what's the current error?

**Comment by absidue** [comment] 2020-08-18 21:01
The original issue has returned.

**Comment by absidue** [comment] 2020-08-18 21:06
Here is the current build log: https://github.com/wstyres/Zebra/runs/1000170692?check_suite_focus=true
The issue is fixed locally and only seems to happen on GitHub Actions.
We were able to mitigate the issue entirely by using the theos commit just before the next changes were merged and the old makefiles.

**Comment by absidue** [comment] 2020-08-18 21:08
Here is the GitHub workflow we are using: https://github.com/wstyres/Zebra/blob/carthage/.github/workflows/build.yml

**Comment by kabiroberai** [comment] 2020-08-18 21:12
I have a feeling this is due to your Header Search Paths setting being recursive. Looking up similar issues online, that's usually what it's been. Not too sure why it's non-deterministically occurring only in CI environments but I doubt that's a Theos-related problem. Try making the header search paths non-recursive to see if that fixes things.

**Comment by absidue** [comment] 2020-08-18 22:06
Thank you very much for your help. I'm closing this as we are no longer facing the issue.

**Comment by kirb** [comment] 2020-08-19 04:42
I think this issue should remain open if we now know the issue is “CocoaPods fails to build with Theos xcodeproj”. Unless I’m mistaken and we believe this was just a misconfiguration of some sort that was specific to the Zebra project setup.

**Comment by kabiroberai** [comment] 2020-08-19 07:41
@kirb CocoaPods works just fine with xcodeproj.mk -- both Sileo and Supercharge use it atm. This issue was related to non-deterministic build failures as a result of recursive header search paths, which is an Xcode issue, not a Theos one. I don't think CocoaPods was actually ever a problem here, it was just one of the cryptic errors Xcode produced. Can we close this again?

**Comment by kirb** [comment] 2020-08-19 07:57
Ah, got it.

**Closed by kirb** 2020-08-19 07:57 UTC

**Comment by kabiroberai** [comment] 2020-08-19 08:03
Changed the title back to the original one for future reference

**Comment by absidue** [comment] 2020-08-19 08:03
We weren't using CocoaPods we had added the dependency's manually, so XCode was building them first and then the main project.

We faced two issues:

1. With the dependencies setup like that we got the `Could not build module ...` errors when using the xcodeproj makefiles. This seemed to be caused by the custom derived data directory. This was resolved when we switched to building the dependencies with Carthage.
2. The cyclic dependency issues in c files. This was resolved by disabling the recursive header search paths and by using the full paths in the imports.

**Comment by kabiroberai** [comment] 2020-08-19 08:06
Would it be possible for you to check whether a custom derived data directory works with manually added frameworks when the header search paths are non-recursive? Also, do you have a build log for when your dependencies were failing to be built?

**Comment by absidue** [comment] 2020-08-19 08:33
I don't seem to have a log for that anymore. I'll try to reproduce the issue and get back to you with some logs.

**Comment by absidue** [comment] 2020-08-20 23:05
Hi @kabiroberai I was able to replicate the issue. Below you can find a commit replicating the issue and two logs one with and without the `messages` variable set to yes.

Commit: https://github.com/absidue/Zebra/commit/e839471bb66a40d8a08ad216078fb5e5b22784cb

Log: https://gist.github.com/absidue/6f72afba86b243f6bb96920eed2ee5d3
Log with `messages=yes`: https://gist.github.com/absidue/bd1e6be1aae13a702061fb4e871baf13

Hope these help.
