### ISSUE TITLE
/Library/PreferenceBundles/Tweak.bundle wrong permissions

### ISSUE THREAD

**Issue by zanderisrael** [theos/theos#455] opened 2019-10-21 00:33 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. make package install

What happens?
-------------
Tweak.bundle is installed with wrong permissions

What were you expecting to happen?
----------------------------------
Tweak.bundle runs when chmod 755

What versions of software are you using?
----------------------------------------
**Operating System:**
MacOS 10.14.6

**Toolchain Version:**
 Theos 2.5

**SDK Version:**
11.4

**Comment by L1ghtmann** [comment] 2023-12-21 17:03
Closing as unable to reproduce with up-to-date tooling. If the issue persists with the latest Theos, please feel free to reopen.

**Closed by L1ghtmann** 2023-12-21 17:03 UTC
