### ISSUE TITLE
Package won't build

### ISSUE THREAD

**Issue by ajaidan** [theos/theos#519] opened 2020-05-31 03:49 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Run make package install on WSL
What happens?
-------------
ERROR: control directory has bad permissions 777 (must be >=0755 and <=0775)

What were you expecting to happen?
----------------------------------
Package would build and create a deb

Any logs, error output, etc?
----------------------------
No.

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** … WIndows/WSL

**Toolchain Version:** … Sam Bingner's ARM64E

**SDK Version:** … 11.2

**Comment by uroboro** [comment] 2020-06-06 16:35
Closing as duplicate of #421

**Closed by uroboro** 2020-06-06 16:35 UTC
