### ISSUE TITLE
[Bug]: Run the installer:   bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)" An error occurred

### ISSUE THREAD

**Issue by Mieing** [theos/theos#821] opened 2024-07-20 10:56 UTC
### What are the steps to reproduce this issue?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

### What happens?

dyld[26638]：missing symbol called

### What were you expecting to happen?

Install the program normally

### What OS are you seeing the problem on?

iOS

### What OS version does it have installed?

iOS15.2.1

### What toolchain and version are you using?

terminal

### Which SDK version are you using?

iOS 15.2.1

### What OS is your client device running?

iOS

### What OS version does it have installed?

ios 15.2.1

### Which device model is it?

xr

### Which jailbreak is it using (if relevant)?

xinaa15

**Comment by leptos-null** [comment] 2024-07-20 18:12
We've seen this a few times. In those cases, the issue was with the `curl` command. Please try installing a different version of `curl` from the package manager.

**Comment by Mieing** [comment] 2024-07-21 17:15
The Procursus repo only has one curl 8.7.1, which cannot be upgraded or downgraded

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Leptos ***@***.***>
发送时间: Sunday, July 21, 2024 2:12:38 AM
收件人: theos/theos ***@***.***>
抄送: Mieing ***@***.***>; Author ***@***.***>
主题: Re: [theos/theos] [Bug]: Run the installer: bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)" An error occurred (Issue #821)


We've seen this a few times. In those cases, the issue was with the curl command. Please try installing a different version of curl from the package manager.

―

**Comment by L1ghtmann** [comment] 2024-07-23 20:49
Unfortunately, there are a number of issues with the XinaA15 v1 bootstrap that are out of our control. You can attempt to download the script manually and then execute it the same was with `bash` in your terminal (e.g., MTerm, NewTerm, etc). It is recommended that you upgrade to v2 as it fixes most, if not all, of the aforementioned bootstrap issues.

**Comment by L1ghtmann** [comment] 2024-08-11 01:23
Closing due to the issue not being caused by Theos. Feel free to reopen if you encounter any other issues!

**Closed by L1ghtmann** 2024-08-11 01:23 UTC
