### ISSUE TITLE
Mobile bugs

### ISSUE THREAD

**Issue by the-casle** [theos/theos#249] opened 2017-05-27 22:57 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Make, make package, or make package install
2. …
3. …

What happens?
-------------
Any above command after a successful compile, then adding a deliberate bug and never updates compiler and says (code shown in ghostbin). installs deb within packages folder instead of compiling the tweak and making a new deb

What were you expecting to happen?
----------------------------------
Actually compiles the updated tweak instead of referring to old debugging report. Then make a deb out of new code instead of old

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
https://ghostbin.com/paste/3727c

Any other comments?
-------------------
Delete obj .theos and packages to make it work right. Above code is after deliberate bugs immediately after a successful compile. Really annoying to delete those three folders after every compile so my edits will be actually compiled. 

What versions of software are you using?
----------------------------------------
**Operating System:** updated before

**Toolchain Version:** update before

**SDK Version:** 9.2

**Comment by kirb** [comment] 2017-05-28 00:42
What is the issue here? Seems to be working as intended.

**Comment by uroboro** [comment] 2017-05-28 01:06
The issue is that after doing:

> $ make do
> edit source files
> $ make do

There are no changes in implementation.

**Comment by candoizo** [comment] 2017-05-28 23:59
@the-casle it sounds like you should use `make clean package` to force a fresh one

**Comment by the-casle** [comment] 2017-05-29 02:55
Shouldn't it compile new files instead of just reading off old debug report. At least urorboro said i shouldn't have to delete the folders every time.

**Comment by candoizo** [comment] 2017-05-29 12:01
I don't believe so if you aren't indicating that you want a fresh package, unless he has explicitly told you otherwise somewhere else. 

My understanding of `make` is that it's simply doing work on whatever files it was told about last with no concern of your file changes until you tell it otherwise (by indicating you want `clean/FINALPACKAGE=1`, or if obviously the staging directory doesn't exist in which case it has to run through it all (which it sounds like you're forcing by deleting those folders))

Maybe you think that it reads the entire project when you call `make` because it has worked to remedy problems when you're compiling (I used to think this, but the deception is that those problems stemmed from the makefile so it didn't matter that I wasn't checking my tweak.xm again), but its still only checking the makefile at that time for changes, and thus is unaware if you have modified your code  in other places


Pretty sure not reading your modified code when asking it to only `make/make package/make do` is intended

**Comment by kirb** [comment] 2017-05-29 13:04
Definitely not – one of make’s key features is not having to rebuild what hasn’t changed! Sorry for misunderstanding you initially, @the-casle.

Are you sure you aren’t possibly saving files with a modified date that’s older than the current system time? Make determines what to build based on file modification dates. If `Tweak.x` was modified on 2017-05-20 at 12:30, and `Tweak.x.o` (the output from the compiler) has a modification date of 2017-05-29 22:21, then there’s no need to rebuild this file because (presumably) the output contains the latest code. Of course, this falls apart if your file dates are messed up, for instance if you’re uploading updated files from your computer to your phone, when the computer is set to a different timezone. You can test that theory by `touch`ing the file from the command line on the phone, then attempting a build again.

Also just for reference – `make clean` will delete build artifacts for you (`.theos/obj` and a few other things). You shouldn’t have to delete any of the other directories, and deleting the entire `.theos` dir will also reset the build counter and force the compiler to rebuild module caches.

**Comment by the-casle** [comment] 2017-05-29 18:05
@kirb sorry for not being clear enough. I've just recently learned that having to delete the files was not intended. I'll check my dates. If you need any other information I would happily send ghostbins

**Comment by uroboro** [comment] 2017-06-07 18:19
This would appear to be an issue in Filza somehow managing to edit files but not modify the modification of dates of said files. Contact them at info@tigisoftware.com regarding this issue.
I'll close this issue for now.

**Closed by uroboro** 2017-06-07 18:19 UTC
Labels: Component: Makefiles, Platform:iOS
