### ISSUE TITLE
error: I can't find the substrate Generator!

### ISSUE THREAD

**Issue by iThanh** [theos/theos#368] opened 2019-01-07 12:05 UTC
Hi,
I got an error when `make package`

```
Could not find or check module 'Logos::Generator::substrate::Generator' [THIS MAY BE A PROBLEM!] at /Users/love/testapp/vendor/logos/bin/lib/Logos/Generator.pm line 43.

AC.xm: error: I can't find the substrate Generator!
make[4]: *** [/Users/love/testapp/.theos/obj/debug/arm64/AC.xm.mm] Error 2
rm /Users/love/testapp/.theos/obj/debug/arm64/AC.xm.mm
make[3]: *** [/Users/love/testapp/.theos/obj/debug/arm64/testapp.dylib] Error 2
make[2]: *** [internal-library-all_] Error 2
make[1]: *** [testapp.all.tweak.variables] Error 2
make: *** [internal-all] Error 2
```

What versions of software are you using?
----------------------------------------
**Operating System:** macOS Mojave

**Toolchain Version:** lastest

**SDK Version:** 10.0

**Comment by kirb** [comment] 2019-01-07 12:10
Fixed (dupe of #369)

**Closed by kirb** 2019-01-07 12:10 UTC
