### ISSUE TITLE
[Bug]: Permission denied at /opt/theos/bin/swift-bootstrapper.pl line 67.

### ISSUE THREAD

**Issue by ALovelyPapa** [theos/theos#805] opened 2024-05-25 12:52 UTC
When I make tweak_swift project, it reports:

**Permission denied at /opt/theos/bin/swift-bootstrapper.pl line 67.**

Apple M2, macOS13.4,  theos latest version

**Comment by L1ghtmann** [comment] 2024-05-29 21:50
Hi @ALovelyPapa, could you provide more context? What command are you running, where is your project directory, etc. Also, for the future, please do not remove the issue template. The requested fields are present to facilitate us helping without having to first clarify additional information as we are now. Thanks!

**Comment by ALovelyPapa** [comment] 2024-06-09 10:57
Hi @L1ghtmann, when I changed the theos installation directory from /opt/theos to ~/theos, the problem resolved, Thanks!

**Comment by leptos-null** [comment] 2024-06-09 20:11
I'm not able to reproduce.
The original Author has resolved by installing theos to the suggested installation directory - closing.

**Closed by leptos-null** 2024-06-09 20:11 UTC
