### ISSUE TITLE
latest theos seems not scanning Xcode 9.3.1's iPhoneOS11.3 SDK? 

### ISSUE THREAD

**Issue by xuanliu-aa** [theos/theos#320] opened 2018-05-23 01:24 UTC
latest theos seems not scanning Xcode 9.3.1's iPhoneOS11.3 SDK? 

What are the steps to reproduce this issue?
-------------------------------------------
1. … I just updated my theos to latest, saying it support scanning Xcode SDKs:

>As of bcd16b4, we now scan for SDKs in both Xcode.app and theos/sdks/. There is currently an issue with the logic that determines the latest available SDK, where 10.1 will be seen as older than 9.3 (but 8.4 is older than 9.3 as expected), which will be fun to fix since macOS’s ancient sort doesn’t have the -V flag. Of course, if you’re using the patched iPhoneOS10.1.sdk, while Xcode 8.2 is installed, you’ll still need to manually specify your SDK version using TARGET; otherwise Theos will use iPhoneOS10.2.sdk because it’s newer. This also only applies to iOS targets at this point (see #242).

2. My Xcode 9.3.1 has below private framework copied:
```
XuanLiuLaptop:PrivateFrameworks xuanliu$ pwd;ls -l
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/System/Library/PrivateFrameworks
total 0
drwxr-xr-x@ 52 root  wheel  1664 May 23 09:19 SpringBoardServices.framework
```
3. My Makefile looks like:
```
XuanLiuLaptop:Open xuanliu$ cat Makefile 
TARGET := iphone:clang:11.3:10.3
ARCHS := armv7 armv7s arm64

include theos/makefiles/common.mk

TOOL_NAME = open
open_FILES = open.m
open_PRIVATE_FRAMEWORKS = SpringBoardServices
open_CODESIGN_FLAGS = -SEntitlements.plist

include $(THEOS_MAKE_PATH)/tool.mk
```

What happens?
it gives error 
```
==> Cleaning…
> Making all for tool open…
==> Compiling open.m (armv7)…
==> Linking tool open (armv7)…
ld: framework not found SpringBoardServices
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/xuanliu/Development/Open/.theos/obj/debug/armv7/open] Error 1
make[2]: *** [/Users/xuanliu/Development/Open/.theos/obj/debug/armv7/open] Error 2
make[1]: *** [internal-tool-all_] Error 2
make: *** [open.all.tool.variables] Error 2
```

What were you expecting to happen?
----------------------------------
make passed

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** latest macOS

**Toolchain Version:** … Not sure

**SDK Version:** … latest Xcode 9.3.1 SDKs

**Comment by kirb** [comment] 2018-05-23 03:40
Not a bug — private frameworks are no longer part of the Apple-provided SDK. You need to download a [patched SDK](https://github.com/theos/sdks), placing the `iPhoneX.X.sdk` in `$THEOS/sdks/`, and then set that version as your target SDK. In your case you’d be using the 11.2 SDK and updating the TARGET line to `TARGET := iphone:clang:11.2:10.3`.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).

**Closed by kirb** 2018-05-23 03:40 UTC

**Comment by xuanliu-aa** [comment] 2018-05-23 03:46
@kirb I manually copied the private frameworks into Xcode SDK path, are you saying even I did this, theos won't scan that private network?

**Comment by kirb** [comment] 2018-05-23 03:57
It should work if placed in `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/PrivateFrameworks`. Is the structure correct? Should be like `…/iPhoneOS.sdk/System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices.tbd`.

Try using `make messages=yes` and look at the command line executed while linking. You should see `-F/Applications/…etcetc…/iPhoneOS10.3.sdk/System/Library/PrivateFrameworks`. Try adding this to your makefile:

```make
open_LDFLAGS += -F$(SYSROOT)/System/Library/PrivateFrameworks -framework SpringBoardServices
```

and comment out the `open_PRIVATE_FRAMEWORKS` line. Shouldn’t use this as a permanent solution, but if it works, use it in the meantime while I try to figure out.

**Comment by xuanliu-aa** [comment] 2018-05-23 04:04
@kirb beforetrying, need to confirm one thing: 
I ONLY copied the framework into `iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/System/Library/PrivateFrameworks`,
but you mentioned 
`Developer/SDKs/iPhoneOS.sdk/System/Library/PrivateFrameworks`

my makefile speicify target ` iphone:clang:11.3:10.3`,

so which SDK it's using? `iPhoneOS.sdk` or `iPhoneOS11.3.sdk`?

**Comment by kirb** [comment] 2018-05-23 05:54
The SDK is in `iPhoneOS.sdk`, but `iPhoneOS11.3.sdk` is a symlink to `iPhoneOS.sdk`.

**Comment by xuanliu-aa** [comment] 2018-05-23 06:05
@kirb
My `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/PrivateFrameworks/SpringBoardServices.framework/` only contains a bunch of headers, no SpringBoardServices.tbd. Is this the problem?


```
XuanLiuLaptop:Open xuanliu$ make messages=yes
set -o pipefail; (mkdir -p /tmp/theos_for_wsl/Open)
> Making all for tool open…
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile --no-keep-going COLOR=1 \
		internal-tool-compile \
		_THEOS_CURRENT_TYPE=tool THEOS_CURRENT_INSTANCE=open _THEOS_CURRENT_OPERATION=compile \
		THEOS_BUILD_DIR="." _THEOS_MAKE_PARALLEL=yes
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile --no-print-directory --no-keep-going internal-tool-compile _THEOS_CURRENT_TYPE="tool" THEOS_CURRENT_INSTANCE="open" _THEOS_CURRENT_OPERATION="compile" THEOS_BUILD_DIR="." THEOS_CURRENT_ARCH="armv7"
set -o pipefail; (mkdir -p /Users/xuanliu/Development/Open/.theos/obj/debug/armv7)
(printf "\e[0;3%im==> \e[1;39m%s…\e[m\n" 3 "Linking tool open (armv7)"); set -o pipefail; (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fcolor-diagnostics -L/Users/xuanliu/Development/Open/theos/lib -L/Users/xuanliu/Development/Open/theos/vendor/lib -lobjc -framework Foundation -framework CoreFoundation     -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/System/Library/PrivateFrameworks  -framework SpringBoardServices         -isysroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk" -miphoneos-version-min=10.3 -Xlinker -segalign -Xlinker 4000 -multiply_defined suppress -arch armv7  -ggdb -O0 -o "/Users/xuanliu/Development/Open/.theos/obj/debug/armv7/open" /Users/xuanliu/Development/Open/.theos/obj/debug/armv7/open.m.7978e7af.o)
==> Linking tool open (armv7)…
ld: framework not found SpringBoardServices
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kirb** [comment] 2018-05-23 06:20
Yes, you need a `.tbd` or binary because this is what the linker consults to build the symbol table. Headers are only used by the compiler.

**Comment by xuanliu-aa** [comment] 2018-05-23 06:20
then that's the root cause. Thanks!
