### ISSUE TITLE
Compilation succeed, but link problems.

### ISSUE THREAD

**Issue by enty8080** [theos/theos#511] opened 2020-05-24 15:53 UTC
**Error with liblaunch.dylib:**

```
> Making all for tool esplios…
==> Linking tool esplios (armv7)…
ld: in '/usr/lib/system/liblaunch.dylib', missing required architecture armv7 in file /usr/lib/system/liblaunch.dylib (2 slices) for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/enty8080/eggshell/src/esplios/.theos/obj/debug/armv7/esplios] Error 1
make[2]: *** [/Users/enty8080/eggshell/src/esplios/.theos/obj/debug/armv7/esplios] Error 2
make[1]: *** [internal-tool-all_] Error 2
make: *** [ios.all.tool.variables] Error 2
```

**Also there is an error with libcrypto.a:**

```
> Making all for tool esplios…
make[3]: *** No rule to make target `libcrypto.a', needed by `/Users/enty8080/eggshell/src/esplios/.theos/obj/debug/armv7/esplios'.  Stop.
make[2]: *** [/Users/enty8080/eggshell/src/esplios/.theos/obj/debug/armv7/esplios] Error 2
make[1]: *** [internal-tool-all_] Error 2
make: *** [ios.all.tool.variables] Error 2
```

**System:**

* `MacOS High Sierra 10.13.6`
* `Xcode 7.2.1`
* `SDK iPhoneOS9.3`
* `Theos latest version`

**Compilation succeed, but link failed!**

**Comment by uroboro** [comment] 2020-06-06 16:03
The liblaunch issue has always eluded me. For that one, this would be a duplicate of #333 which is already a pinned issue.

For the libcrypto one, you're using a rather old configuration but I'll ask to share your project makefile

**Comment by enty8080** [comment] 2020-06-10 09:16
@uroboro 
```makefile
include $(THEOS)/makefiles/common.mk
export SYSROOT = /opt/theos/sdks/iPhoneOS9.3.sdk
export TARGET_CODESIGN_FLAGS="-Ssign.plist"
TOOL_NAME = esplios

esplios_FILES = main.mm espl.m
esplios_OBJ_FILES = libcrypto.a libssl.a
esplios_FRAMEWORKS = Foundation Security AudioToolbox CoreFoundation AVFoundation MediaPlayer UIKit
esplios_PRIVATE_FRAMEWORKS = AppSupport SpringBoardServices IOSurface

include $(THEOS_MAKE_PATH)/tool.mk

export ARCHS = armv7 arm64

CFLAGS = -Wall -g
```

**Comment by uroboro** [comment] 2020-06-13 20:26
`export ARCHS = armv7 arm64` has to go before the `include $(THEOS)/makefiles/common.mk` line. Otherwise it is ignored

**Comment by enty8080** [comment] 2020-06-13 22:46
> `export ARCHS = armv7 arm64` has to go before the `include $(THEOS)/makefiles/common.mk` line. Otherwise it is ignored

@uroboro This is a fix for `libcrypto.a`?

**Comment by L1ghtmann** [comment] 2024-06-08 19:11
`XXX_OBJ_FILES` is an internal variable used to track object files (.o) for creation of the final product. Here you are essentially telling Theos that those two files are now dependencies of the final product, yet they don't exist. If you want to link them against your project, you'd want to specify them in the `XXX_LIBRARIES` variable (e.g., XXX_LIBRARIES = crypto) with the libraries, compiled for iOS, placed in $THEOS/lib.

**Closed** 2024-06-09 13:07 UTC
