### ISSUE TITLE
[Bug]: Can't compile tweaks after updating to macOS Sonoma + Xcode 15

### ISSUE THREAD

**Issue by ItzNebbs** [theos/theos#742] opened 2023-06-07 00:00 UTC
### What are the steps to reproduce this issue?

1. Update to macOS Sonoma and/or Xcode 15
2. Run "make clean do" and error occurs when linking

### What happens?

(Note: I have just made different shell files for compiling for rootless/rootful, but the command run is "make clean do")

### What were you expecting to happen?

Compile as normal

### Paste any relevant logs, error output, etc.

```shell
nebbs@Nebbs-MacBook-Air Twister % ./rootful_install.sh
==> Cleaning…
> Making clean in preferences…
==> Cleaning…
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
==> Warning: Building for iOS 9.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> Making all for tweak Twister…
==> Compiling helpers/TwisterAnimator.swift (arm64)…
<unknown>:0: remark: unable to perform implicit import of "_StringProcessing" module: no such module found
==> Generating Twister-Swift.h (arm64)…
<unknown>:0: remark: unable to perform implicit import of "_StringProcessing" module: no such module found
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
==> Compiling helpers/CALayer+Twister.m (arm64)…
==> Compiling helpers/TWSLua.m (arm64)…
==> Linking tweak Twister (arm64)…
ld: warning: -multiply_defined is obsolete
ld: warning: ignoring duplicate library '-lc++'
ld: warning: search path '/Users/nebbs/theos/vendor/lib/iphone/rootful' not found
ld: error parsing '/Users/nebbs/theos/sdks/iPhoneOS15.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit.tbd': tapi error: malformed file
/Users/nebbs/theos/sdks/iPhoneOS15.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit.tbd:3:24: error: unknown platform
platform:              (null)
                       ^~~~~~

ld: error parsing '/Users/nebbs/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd': tapi error: malformed file
/Users/nebbs/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd:3:18: error: unknown platform
platform:        iphoneos
                 ^~~~~~~~

ld: error parsing '/Users/nebbs/theos/sdks/iPhoneOS15.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation.tbd': tapi error: malformed file
/Users/nebbs/theos/sdks/iPhoneOS15.0.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation.tbd:3:24: error: unknown platform
platform:              (null)
                       ^~~~~~

ld: error parsing '/Users/nebbs/theos/sdks/iPhoneOS15.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation.tbd': tapi error: malformed file
/Users/nebbs/theos/sdks/iPhoneOS15.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation.tbd:3:24: error: unknown platform
platform:              (null)
                       ^~~~~~

ld: parsing files failed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/nebbs/Desktop/Jailbreaking/Tweaks/Twister/.theos/obj/arm64/Twister.dylib] Error 1
make[2]: *** [/Users/nebbs/Desktop/Jailbreaking/Tweaks/Twister/.theos/obj/arm64/Twister.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [Twister.all.tweak.variables] Error 2
nebbs@Nebbs-MacBook-Air Twister %
```

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

14.0 Beta 1

### What toolchain and version are you using?

Xcode 15 Beta 1

### Which SDK version are you using?

15.0

### What OS is your client device running?

iOS

### What OS version does it have installed?

15.7.6

### Which device model is it?

iPhone 7 Plus

### Which jailbreak is it using (if relevant)?

palera1n rootful

**Comment by leptos-null** [comment] 2023-06-10 19:30
It looks like `ld64-902.11` is version of `ld` in Xcode 14.0 beta 1. 
This version of `ld` evidently requires using the `targets` field instead of the `archs` and `platform` fields.
The Theos [iOS 14.5 SDK](https://github.com/theos/sdks/blob/bb425abf3acae8eac328b828628b82df544d2774/iPhoneOS14.5.sdk) uses the updated format.

Overall, I do not believe Theos requires any changes for this, although we should update the `.tbd`s shipped in [theos/lib](https://github.com/theos/lib)

**Comment by kabiroberai** [comment] 2023-06-14 00:25
Could you please run `make clean all messages=yes` and share the output? Also try `instance_LDFLAGS = -ld64` because Xcode 15 uses a new `ld-prime` linker by default which may have some incompatibilities with Theos atm.

**Comment by kabiroberai** [comment] 2023-06-14 00:41
Update: after looking into this a bit more it seems like the SDK is one part of the issue but the other is that CydiaSubstrate.tbd uses `iphoneos` rather than `ios` as the platform. That's something that we need to fix in theos/lib.

**Comment by L1ghtmann** [comment] 2023-07-16 20:24
@ItzNebbs would you mind updating Theos (make update-theos or $THEOS/bin/update-theos) and trying your project again? https://github.com/theos/lib/pull/19 was just merged.

**Comment by leptos-null** [comment] 2023-07-30 20:32
I've tested with a blank project on macOS Sonoma. I'm able to reproduce when `vendor/lib` is checked out at <https://github.com/theos/lib/commit/a27acf42f7d72eb8d7cf52ecf504d1d871155680> and _not_ able to reproduce when checkout out at <https://github.com/theos/lib/commit/3d7033b3c54e074f3da409771475f16dfefb046b>.

**Closed by leptos-null** 2023-07-30 20:32 UTC
