### ISSUE TITLE
LZMA Invalid Option 0

### ISSUE THREAD

**Issue by JeffResc** [theos/theos#379] opened 2019-02-23 06:00 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. Follow the iOS installation steps accordingly.
2. Try to ```make do``` on a valid package.

What happens?
-------------
```lzma: invalid option -- 0```

What were you expecting to happen?
----------------------------------
Package to successfully complile.

Any logs, error output, etc?
----------------------------
```bash
Jeffs-iPhone:~/ShortLook-Steam root# make clean && make do
==> Cleaning…
> Making all for bundle ShortLook-Discord…
==> Compiling DiscordContactPhotoProvider.m (armv7)…
==> Compiling DiscordContactPhotoProvider.m (arm64)…
==> Linking bundle ShortLook-Discord (arm64)…
==> Generating debug symbols for ShortLook-Discord…
==> Linking bundle ShortLook-Discord (armv7)…
==> Generating debug symbols for ShortLook-Discord…
==> Merging bundle ShortLook-Discord…
==> Signing ShortLook-Discord…
> Making stage for bundle ShortLook-Discord…
dm.pl: building package `com.jeffresc.shortlook.plugin.contact-photo.discord:iphoneos-ar m' in `./packages/com.jeffresc.shortlook.plugin.contact-photo.discord_1.0.1-6+debug_ipho neos-arm.deb'
lzma: invalid option -- 0
make: *** [/var/root/theos/makefiles/package/deb.mk:58: internal-package] Error 141
```

Any other comments?
-------------------
Theos Dependencies is installed, LZMA is installed and all other dependencies should be installed and functioning correctly.

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 12.1.2

**Toolchain Version:** 6.1-1 (via BigBoss by CoolStar)

**SDK Version:** 11.2 (from the [SDK Repo](https://github.com/theos/sdks))

**Comment by kirb** [comment] 2019-02-23 06:08
Duplicate of theos/dm.pl#12.

**Closed by kirb** 2019-02-23 06:08 UTC
