### ISSUE TITLE
[Bug]: Can't include other makefile in `Makefile`

### ISSUE THREAD

**Issue by itsjunetime** [theos/theos#794] opened 2024-03-08 18:17 UTC
### What are the steps to reproduce this issue?

1. Make new project with `nic.pl` (I only tried with making a tweak so far)
2. `cd` into the new project directory
3. `echo "ARHCS = arm64" > other_makefile.mk`
4. Open `Makefile` and replace the `ARCHS = ...` line with `include ./other_makefile.mk`
5. Run `make package`

### What happens?

`make package` outputs the following instead of compiling successfully:
```
> Making all for tweak bugrepro…
gmake[1]: *** No rule to make target 'internal-tweak-all'.  Stop.
gmake: *** [/Users/june/theos/makefiles/master/rules.mk:146: bugrepro.all.tweak.variables] Error 2
```

### What were you expecting to happen?

A successful compilation and packaging

### Additional context

Making a new project without modifying the Makefile as described above allows me to compile successfully, so this isn't a problem with my machine. Additionally, adding the `include other_makefile.mk` after the `include $(THEOS)/makefiles/common.mk` allows the project to compile successfully, but that unfortunately doesn't fix my problem because I need to use the other Makefile to set variables before including `common.mk`.

As far as I can tell ([according to the gnu make manual](https://www.gnu.org/software/make/manual/html_node/Include.html)), I'm using the include directive successfully. I've also tried to use a fully-qualified path to include (`include $(CURDIR)/other_makefile.mk`), but that results in the same error.

I've tried this with both make 3.81 (packaged with macOS) and 4.4.1 (installed from homebrew) and the issue appears with both of them. The only difference is that 4.4.1 contains the file+line trace, while 3.81 omits it.

### What OS are you seeing the problem on?

macOS

### What OS version does it have installed?

macOS 14.2.1

### What toolchain and version are you using?

Xcode 11.7, Xcode 15.2

### Which SDK version are you using?

13.7

### What OS is your client device running?

iOS

### What OS version does it have installed?

15.8

### Which device model is it?

iPhone 6s

**Comment by kirb** [comment] 2024-03-21 04:57
I was able to reproduce this (thanks heaps for figuring out the minimal repro steps) but I can’t explain why it doesn’t work. Perhaps this needs to be reported upstream to GNU Make.

**Comment by L1ghtmann** [comment] 2024-06-09 14:30
I can replicate on Linux (WSL) with Make 4.3-4.1, though it is not a Make issue.

The logic break occurs @ https://github.com/theos/theos/blob/cd71cfc5b41832268d2b0cd1fca3de000e678e16/makefiles/master/rules.mk#L165-L171 and appears to fail irrespective of the project type.

**before:**
```
make -f Makefile --no-keep-going COLOR=1 --no-print-directory internal-tool-all _THEOS_CURRENT_TYPE=tool THEOS_CURRENT_INSTANCE=test2 _THEOS_CURRENT_OPERATION=all THEOS_BUILD_DIR=.
```

**after:**
```
make -f other.mk --no-keep-going COLOR=1 --no-print-directory internal-tool-all _THEOS_CURRENT_TYPE=tool THEOS_CURRENT_INSTANCE=test2 _THEOS_CURRENT_OPERATION=all THEOS_BUILD_DIR=.
```

Notice the argument passed to `-f`.

This is handled by https://github.com/theos/theos/blob/cd71cfc5b41832268d2b0cd1fca3de000e678e16/makefiles/common.mk#L48-L51

- When including common.mk above other.mk, `_THEOS_PROJECT_MAKEFILE_NAME` the list, at the time of evaluation, only includes the main Makefile
- When including other.mk below common.mk, `_THEOS_PROJECT_MAKEFILE_NAME` gets assigned to other.mk as it is the last item in the list, causing it to be used as the project makefile.
  - It seems as though `Makefile` is always listed first as it is the primary makefile being evaluated and others are tacked on after

The solution seems to be changing 
```make
export _THEOS_PROJECT_MAKEFILE_NAME := $(notdir $(lastword $(_THEOS_STATIC_MAKEFILE_LIST)))
```

to

```make
export _THEOS_PROJECT_MAKEFILE_NAME := $(notdir $(firstword $(_THEOS_STATIC_MAKEFILE_LIST)))

```

This works for:
- other.mk before common.mk
- other.mk after common.mk
- no other.mk at all

**Closed** 2024-06-13 23:59 UTC
