### ISSUE TITLE
Add info about Preferences Loader requirement

### ISSUE THREAD

**Issue by krisanovdev** [theos/theos#443] opened 2019-09-05 18:22 UTC
What are the steps to reproduce this issue?

1. create tweak and preferences bundle (bin/nic.pl)
2. run `make package install`
3. go to settings

What happens?
There is no preferences for new tweak. This is because Preference Loader not installed. It should be described in wiki.

What were you expecting to happen?
There is information about Preference Loader requirement in wiki.

If you approve it, I can create PR.

**Comment by uroboro** [comment] 2022-02-19 18:29
Duplicate of https://github.com/theos/templates/issues/12

**Closed by uroboro** 2022-02-19 18:29 UTC
