### ISSUE TITLE
Theos on checkra1n iOS 13.2.3 broken

### ISSUE THREAD

**Issue by KP2048** [theos/theos#467] opened 2019-12-09 19:34 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Install theos on iOS device running checkra1n 
2. run make package
3. realize that checkra1n doesn’t include fakeroot in /bin

What happens?
-------------
Error 137

What were you expecting to happen?
----------------------------------
My tweak to compile 

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

WitherTech-iPhone:~/Sandbox mobile$ make package   
> Making all for tweak CydiaRespring…              
==> Preprocessing Tweak.xm…                        
==> Preprocessing Tweak.xm…                        
==> Compiling Tweak.xm (arm64)…                    
==> Compiling Tweak.xm (armv7)…                    
==> Linking tweak CydiaRespring (arm64)…           
==> Generating debug symbols for CydiaRespring…    
rm /var/mobile/Sandbox/.theos/obj/debug/arm64/Tweak.xm.mm                                              
==> Linking tweak CydiaRespring (armv7)…           
==> Generating debug symbols for CydiaRespring…    
rm /var/mobile/Sandbox/.theos/obj/debug/armv7/Tweak.xm.mm                                              
==> Merging tweak CydiaRespring…                   
==> Signing CydiaRespring…                         
> Making stage for tweak CydiaRespring…            
/usr/bin/fakeroot: line 181:  5856 Killed: 9       
       FAKEROOTKEY=$FAKEROOTKEY DYLD_INSERT_LIBRARIES="$LIB" "$@"                                      
make: *** [/var/mobile/theos/makefiles/package/deb.mk:60: internal-package] Error 137                  
WitherTech-iPhone:~/Sandbox mobile$              

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 

**Toolchain Version:** …

**SDK Version:** …

**Comment by Witherking25** [comment] 2019-12-09 19:36
I installed fakeroot from the bingner repo but it is a shell script in /usr/bin that runs /bin/fakeroot

**Comment by Witherking25** [comment] 2019-12-09 19:46
I’m temporarily using dpkg-deb -b _ in the .theos folder to manually build the deb

**Comment by JannikCrack** [comment] 2019-12-20 11:10
> I’m temporarily using dpkg-deb -b _ in the .theos folder to manually build the deb

can you explain what excactly you have done?

**Comment by Witherking25** [comment] 2019-12-28 17:05
Theos actually builds everything, but The deb file is unable to be generated. I can manually generate it with dpkg-deb using the .theos/_ folder as the package folder for dpkg-deb -b

**Comment by Witherking25** [comment] 2019-12-28 17:09
The tweak built in this fashion functions fine. The part of theos that generates the deb is broken on checkra1n

**Comment by gsbarreto** [comment] 2019-12-28 17:20
I'm trying to do use "dpkg-deb -b _" but when i'm going to install using Filza it doesn't work!

**Comment by Witherking25** [comment] 2019-12-28 17:25
You have to do the make package command and then you have to cd into the .theos folder. You then do the dpkg

**Comment by Witherking25** [comment] 2019-12-28 17:27
Can you extract the deb?

**Comment by Witherking25** [comment] 2019-12-28 17:28
Does this tweak work when compiled on a Mac?

**Comment by Witherking25** [comment] 2019-12-28 17:29
What does Filza say when you attempt to install it?

**Comment by gsbarreto** [comment] 2019-12-28 17:32
I managed to extract the deb. I don't have a Mac to test it :/. Filza goes to the installation page but just got a blank page with Install and Done.

**Comment by Witherking25** [comment] 2019-12-28 17:32
What is in the extracted deb?

**Comment by gsbarreto** [comment] 2019-12-28 17:35
2 folders 
- DEBIAN
- Library

**Comment by Witherking25** [comment] 2019-12-28 17:36
What’s in the control file?

**Comment by gsbarreto** [comment] 2019-12-28 17:40
Package: com.yourcompany.welcomewagon
Name: WelcomeWagon
Depends: mobilesubstrate
Architecture: iphone-arm
Description: An awesome MobileSubtrate tweak!
Maintainer: Mobile
Author: Mobile
Section: Tweaks
Version: 0.0.1-6+debug
Istalled-Size: 120

**Comment by Witherking25** [comment] 2019-12-28 17:41
Try installing the deb with dpkg -i <path to deb>

**Comment by Witherking25** [comment] 2019-12-28 17:42
dpkg -i path to deb

**Comment by gsbarreto** [comment] 2019-12-28 17:45
It works! Thanks @Witherking25 !

**Comment by Witherking25** [comment] 2019-12-28 17:46
It was Filza being weird. The deb was not malformed.

**Comment by ConorTheDev** [comment] 2019-12-28 20:28
Duplicate of #459?

**Comment by Witherking25** [comment] 2019-12-28 20:28
Nope

**Comment by Witherking25** [comment] 2019-12-28 20:29
Different issue

**Comment by Karveit** [comment] 2020-01-01 10:16
Edit file "fakeroot.sh"
"$fakeroot $cmd" -> "$fakeroot perl /var/theos/bin/$cmd"
make package is OK
It is just a temporary solution.

**Comment by bubrakshahik** [comment] 2020-04-13 13:48
> Different issue
if you tried all things then make an issue here  
https://github.com/bubrakshahik/bubrakshahik.github.io/issues

**Comment by iplovings** [comment] 2020-10-24 02:31
![image](https://user-images.githubusercontent.com/64208426/97065997-60370c80-1566-11eb-9f91-fa5243f2fa05.png)I am also getting errors pls help

**Comment by Parsa2820** [comment] 2021-03-21 17:09
> 
> 
> Edit file "fakeroot.sh"
> "$fakeroot $cmd" -> "$fakeroot perl /var/theos/bin/$cmd"
> Delete your Project inside ".theos"
> make package again is OK
> It is just a temporary solution.

Thanks a lot. This worked for me.

**Comment by L1ghtmann** [comment] 2024-06-08 17:22
> I installed fakeroot from the bingner repo but it is a shell script in /usr/bin that runs /bin/fakeroot

This seems to be an issue with either the fakeroot package on checkra1n or the permissions given to the fakeroot bin/folder where it is executed. Closing as not Theos related.

**Closed by L1ghtmann** 2024-06-08 17:22 UTC
