### ISSUE TITLE
liblaunch.dylib not found for armv7 error while 'make package'

### ISSUE THREAD

**Issue by iammruni** [theos/theos#297] opened 2018-03-13 19:55 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Create a Tweak
2. Execute: make package

What happens?
-------------
I receive this error:
>Making all for tweak ...
linking tweak ... (armv7)
Ld: file not found /usr/lib/system/liblaunch.dylib for architecture armv7
clang-5.0: error: linker command failed with exit code 1

What were you expecting to happen?
----------------------------------
The package being built

What versions of software are you using?
----------------------------------------
**Operating System:** 9.3.3

**Toolchain Version:**6.1-1

**SDK Version:**9.3

More Info
---------
I have installed Stashing for iOS 9.2-9.3.5 from CoolStar's Repo.
Can this be a reason?
When I open the path: /usr/lib/
System folder is missing has no dylib files there.

**Comment by kirb** [comment] 2018-03-13 21:25
Duplicate of theos/sdks#10.

**Closed by kirb** 2018-03-13 21:25 UTC
