### ISSUE TITLE
Tweaks built for tvOS reference /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate causing them not to load

### ISSUE THREAD

**Issue by Diatrus** [theos/theos#400] opened 2019-04-07 23:38 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Build a tweak for tvOS and attempt to have it inject.

What happens?
-------------
Tweak will not inject and console will throw an error similar to
`Injection failed: 'dlopen(/usr/lib/TweakInject/WiivampTV.dylib, 9): Library not loaded: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate
  Referenced from: /usr/lib/TweakInject/WiivampTV.dylib
  Reason: image not found'`

What were you expecting to happen?
----------------------------------
Tweak should inject and not reference CydiaSubstrate, as nito himself has stated /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate should not, and will not be symlinked with his jailbreak.

Any logs, error output, etc?
----------------------------
Maybe relevant: `ld: warning: invalid -install_name (/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate) in dependent dylib (/Users/diatrus/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd). Dylibs/frameworks which might go in dyld shared cache cannot link with dylibs that won't be in the shared cache`

Any other comments?
-------------------
Nito himself has stated /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate should not, and will not be symlinked to /usr/lib/libsubstrate.dylib with his jailbreak, and this is intended behavior.

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 10.13.6

**SDK Version:** AppleTVOS11.3

**Comment by uroboro** [comment] 2019-04-07 23:46
Did you set the generator as `internal`?

**Comment by Diatrus** [comment] 2019-04-09 22:39
Same result with internal generator.

**Comment by kirb** [comment] 2019-04-10 09:06
I discussed this with @nitoTV, the framework symlink should be there but is missing by mistake. Till he fixes it, you can make it yourself: 

```shell
mkdir -p /Library/Frameworks/CydiaSubstrate.framework
ln -s /usr/lib/libsubstrate.dylib /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate
```

Theos’s side is working as intended, so closing.

**Closed by kirb** 2019-04-10 09:06 UTC
Labels: Pending Reporter Response
