### ISSUE TITLE
Logo can't parse something that I'm pretty sure it should

### ISSUE THREAD

**Issue by fxfactorial** [theos/theos#155] opened 2016-04-10 06:25 UTC
Here is this code:

```objectice-c
%hook NSURLSession
-(NSURLSessionDataTask *)dataTaskWithRequest:(NSURLRequest *)request
			   completionHandler:(void (^)(NSData *data,
						       NSURLResponse *response,
						       NSError *error))cb
{
  %log;

  HBLogInfo(@"Called datatask with request: %@, headers: %@",
	    request,
	    [request allHTTPHeaderFields]);

  return %orig(request, ^(NSData *wrapped_data,
			  NSURLResponse *wrapped_resp,
			  NSError *wrapped_error){
		 HBLogInfo(@"Calling from wrapped callback");
		 cb(wrapped_data, wrapped_resp, wrapped_error);
    });
}

%end
```

and I'm pretty sure that that is correct but logos craps out with `error: missing closing parenthesis` with no suggestion as to where the error is...

I think it should be able to parse this.

and it is able to parse it once i name the block and pass it by that name. I guess a small inconvenience.

**Comment by kirb** [comment] 2016-04-10 06:29
Any difference if you have the block arguments on a single line, in both the method signature and the %orig call?

**Comment by fxfactorial** [comment] 2016-04-10 06:31
@kirb no but it does parse correctly if I put it all on one line:

```
  return %orig(request, ^(NSData *wrapped_data, NSURLResponse *wrapped_resp, NSError *wrapped_error){ HBLogInfo(@"Calling from wrapped callback"); cb(wrapped_data, wrapped_resp, wrapped_error); });
```

**Comment by uroboro** [comment] 2016-04-10 12:28
Closing as duplicate of #83.

**Closed by uroboro** 2016-04-10 12:28 UTC
