### ISSUE TITLE
Tweak.xm:error: unknown type name 'WCMediaItem' static WCMediaItem * _logos_method$_ungrouped$WCContentItemViewTemplateN..

### ISSUE THREAD

**Issue by eveloson** [theos/theos#218] opened 2016-12-31 11:18 UTC
Is theos not support return a instance?,I have already declare  WCMediaItem in header.
```

#import "iOSREWCVideoDownloader.h"
static MMTableViewCell *iOSRECell;
static MMTableView *iOSREView;
static WCTimeLineViewController *iOSREController;
%hook WCContentItemViewTemplateNewSight
%new
- (WCMediaItem *)iOSREMediaItemFromSight
{
      id responder = self;
      while (![responder isKindOfClass:NSClassFromString(@"WCTimeLineViewController")])
      {
            if ([responder isKindOfClass:NSClassFromString(@"MMTableViewCell")]) iOSRECell = responder;
            else if ([responder isKindOfClass:NSClassFromString(@"MMTableView")]) iOSREView = responder;
            responder = [responder nextResponder];
      }
      iOSREController = responder;
      if (!iOSRECell || !iOSREView || !iOSREController)
      {
            NSLog(@"iOSRE: Failed to get video object.");
            return nil;
      }
      NSIndexPath *indexPath = [iOSREView indexPathForCell:iOSRECell];
      int itemIndex = [iOSREController calcDataItemIndex:[indexPath section]];
      WCFacade *facade = [(MMServiceCenter *)[%c(MMServiceCenter) defaultCenter] getService:[%c(WCFacade) class]];
      WCDataItem *dataItem = [facade getTimelineDataItemOfIndex:itemIndex];
      WCContentItem *contentItem = dataItem.contentObj;
      WCMediaItem *mediaItem = [contentItem.mediaList count] != 0 ? (contentItem.mediaList)[0] : nil;
      return mediaItem;
}
%new
- (void)iOSREOnSaveToDisk
{
      NSString *localPath = [[self iOSREMediaItemFromSight] pathForSightData];
      UISaveVideoAtPathToSavedPhotosAlbum(localPath, nil, nil, nil);
}
%new
- (void)iOSREOnCopyURL
{
      UIPasteboard *pasteboard = [UIPasteboard generalPasteboard];
      pasteboard.string = [self iOSREMediaItemFromSight].dataUrl.url;
}
static int iOSRECounter;
- (void)onLongTouch
{
      iOSRECounter++;
      if (iOSRECounter % 2 == 0) return;
      [self becomeFirstResponder];
      UIMenuItem *saveToDiskMenuItem = [[UIMenuItem alloc] initWithTitle:@"Save to Disk" action:@selector(iOSREOnSaveToDisk)];
      UIMenuItem *copyURLMenuItem = [[UIMenuItem alloc] initWithTitle:@"Copy URL" action:@selector(iOSREOnCopyURL)];
      UIMenuController *menuController = [UIMenuController sharedMenuController];
      [menuController setMenuItems:@[saveToDiskMenuItem, copyURLMenuItem]];
      [menuController setTargetRect:CGRectZero inView:self];
      [menuController setMenuVisible:YES animated:YES];
      [saveToDiskMenuItem release];
      [copyURLMenuItem release];
}
%end
```

After I change code like below ,it works.

```
#import "iOSREWCVideoDownloader.h"
static MMTableViewCell *iOSRECell;
static MMTableView *iOSREView;
static WCTimeLineViewController *iOSREController;
%hook WCContentItemViewTemplateNewSight
- (void)iOSREOnSaveToDisk
{
  id responder = self;
      while (![responder isKindOfClass:NSClassFromString(@"WCTimeLineViewController")])
      {
            if ([responder isKindOfClass:NSClassFromString(@"MMTableViewCell")]) iOSRECell = responder;
            else if ([responder isKindOfClass:NSClassFromString(@"MMTableView")]) iOSREView = responder;
            responder = [responder nextResponder];
      }
      iOSREController = responder;
      if (!iOSRECell || !iOSREView || !iOSREController)
      {
            NSLog(@"iOSRE: Failed to get video object.");
            return nil;
      }
      NSIndexPath *indexPath = [iOSREView indexPathForCell:iOSRECell];
      int itemIndex = [iOSREController calcDataItemIndex:[indexPath section]];
      WCFacade *facade = [(MMServiceCenter *)[%c(MMServiceCenter) defaultCenter] getService:[%c(WCFacade) class]];
      WCDataItem *dataItem = [facade getTimelineDataItemOfIndex:itemIndex];
      WCContentItem *contentItem = dataItem.contentObj;
      WCMediaItem *mediaItem = [contentItem.mediaList count] != 0 ? (contentItem.mediaList)[0] : nil;
      UIPasteboard *pasteboard = [UIPasteboard generalPasteboard];
      pasteboard.string = mediaItem .dataUrl.url;
}
static int iOSRECounter;
- (void)onLongTouch
{
      iOSRECounter++;
      if (iOSRECounter % 2 == 0) return;
      [self becomeFirstResponder];
      UIMenuItem *saveToDiskMenuItem = [[UIMenuItem alloc] initWithTitle:@"Save to Disk" action:@selector(iOSREOnSaveToDisk)];
      UIMenuItem *copyURLMenuItem = [[UIMenuItem alloc] initWithTitle:@"Copy URL" action:@selector(iOSREOnCopyURL)];
      UIMenuController *menuController = [UIMenuController sharedMenuController];
      [menuController setMenuItems:@[saveToDiskMenuItem, copyURLMenuItem]];
      [menuController setTargetRect:CGRectZero inView:self];
      [menuController setMenuVisible:YES animated:YES];
      [saveToDiskMenuItem release];
      [copyURLMenuItem release];
}
%end
```
Does it means that I can't add a method with a non-empty  return value for reuse？

**Comment by kirb** [comment] 2017-01-02 05:22
I don’t understand what the problem is here – you’ve provided a vague explanation of the issue and included a heap of code that is probably irrelevant.

Please [use the issue template](https://github.com/theos/theos/blob/master/.github/ISSUE_TEMPLATE.md), and create a test project to create a concise test case – remove all irrelevant code until you end up with only the code that is causing this issue.

**Comment by mstg** [comment] 2017-01-03 08:15
As I have understood it, this is not a problem with theos. If you are sure this is a theos problem use the issue template as pointed out above. Im closing this issue.

---

If you need further help you can ask in the `#theos` channel on `irc.saurik.com`

For more information about IRC, you can read this [wiki article](http://iphonedevwiki.net/index.php/How_to_use_IRC)

**Closed by mstg** 2017-01-03 08:15 UTC
