### ISSUE TITLE
Theos isn’t making package (checkra1n)

### ISSUE THREAD

**Issue by Regularcheckm8** [theos/theos#464] opened 2019-12-03 01:12 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. install Theos  #on iOS **(iOS 13+)**
2.create a tweak
3. run `make package install`

What happens?
-------------
It gives me this:
```ruby

Damn:/var/mobile/test root# make package install
> Making all for tweak test…
==> Preprocessing Tweak.x…
Experimental shift on scalar is now forbidden at /private/var/theos/vendor/logos/bin/lib/Logos/Group.pm line 107, near "$args;"
Experimental shift on scalar is now forbidden at /private/var/theos/vendor/logos/bin/lib/Logos/Group.pm line 108, near "$args;"
Compilation failed in require at (eval 10) line 1.
BEGIN failed--compilation aborted at (eval 10) line 1.
 at /var/theos/bin/logos.pl line 22.
BEGIN failed--compilation aborted at /var/theos/bin/logos.pl line 22.
make[3]: *** [/var/theos/makefiles/instance/rules.mk:256: /var/mobile/test/.theos/obj/debug/arm64/Tweak.x.m] Error 255
rm /var/mobile/test/.theos/obj/debug/arm64/Tweak.x.m
==> Preprocessing Tweak.x…
Experimental shift on scalar is now forbidden at /private/var/theos/vendor/logos/bin/lib/Logos/Group.pm line 107, near "$args;"
Experimental shift on scalar is now forbidden at /private/var/theos/vendor/logos/bin/lib/Logos/Group.pm line 108, near "$args;"
Compilation failed in require at (eval 10) line 1.
BEGIN failed--compilation aborted at (eval 10) line 1.
 at /var/theos/bin/logos.pl line 22.
BEGIN failed--compilation aborted at /var/theos/bin/logos.pl line 22.
make[3]: *** [/var/theos/makefiles/instance/rules.mk:256: /var/mobile/test/.theos/obj/debug/armv7/Tweak.x.m] Error 255
rm /var/mobile/test/.theos/obj/debug/armv7/Tweak.x.m
make[2]: *** [/var/theos/makefiles/instance/library.mk:33: /var/mobile/test/.theos/obj/debug/armv7/test.dylib] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [/var/theos/makefiles/instance/library.mk:33: /var/mobile/test/.theos/obj/debug/arm64/test.dylib] Error 2
make[1]: *** [/var/theos/makefiles/instance/library.mk:24: internal-library-all_] Error 2
make: *** [/var/theos/makefiles/master/rules.mk:111: test.all.tweak.variables] Error 2
```
Any other comments?
-------------------
It wouldn’t give me a `.deb` in the end so it didn’t even do a thing 

What versions of software are you using?
----------------------------------------
**Operating System:** iOS (iOS 13)

**Toolchain Version:** ?

**SDK Version:** IPhoneOS 11.2.sdk

**Comment by kirb** [comment] 2019-12-03 02:49
Duplicate of https://github.com/theos/logos/issues/48. 

You should change your profile picture. Using an established community member’s identity isn’t cool.

**Closed by kirb** 2019-12-03 02:49 UTC
