### ISSUE TITLE
Running a tool on iOS 12 (Chimera) results in Killed 9

### ISSUE THREAD

**Issue by andermoran** [theos/theos#433] opened 2019-08-13 15:20 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Run nic.pl and select iphone/tool
2. cd into the new project and run `make do`
3. Try to run the new tool from the command line on iOS device

What happens?
-------------
Using the default configuration of a tool project, I get the result `Killed 9` when I run it on my iPhone 6S on 12.1.1 running the Chimera jailbreak.

What were you expecting to happen?
----------------------------------
My code was the default template code which is 
```
#include <stdio.h>

int main(int argc, char *argv[], char *envp[]) {
	printf("Hello world!\n");
	return 0;
}
```
so I expected it to print "Hello, world!"

Any logs, error output, etc?
----------------------------
Nope.

Any other comments?
-------------------
I am able to create, build, and install theos tweak projects perfectly fine on my iOS device but for some reason running a tool project on my iOS device gives me the error above. My tool was tested on two iOS 12 devices (iPhone 6S and iPhone XS) on 12.1.1 running Chimera

What versions of software are you using?
----------------------------------------
**Operating System:** macOS Mojave 10.14.5

**Toolchain Version:** Unsure

**SDK Version:** I think iPhoneOS12.1.sdk but it shouldn't matter because the sdk that I'm using works for building tweaks just fine

**Comment by uroboro** [comment] 2019-08-13 15:51
Closing as duplicate of https://github.com/theos/templates/issues/11

**Closed by uroboro** 2019-08-13 15:51 UTC

**Comment by andermoran** [comment] 2019-08-13 16:25
Even after creating an ent.plist file in the project directory and adding `tester_CODESIGN_FLAGS = -S ent.plist` to my Makefile (where _tester_ is the name of my project), I still get the `Killed 9` error. The solution provided by @Muirey03 in [theos/templates#11](https://github.com/theos/templates/issues/11) did not work for me.

**Comment by andermoran** [comment] 2019-08-13 16:32
**Solution:** I was able to fix the `Killed 9` error by making my ent.plist contain

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>platform-application</key>
    <true/>
</dict>
</plist>
```
**NOT**

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>platform-application</key>
    <true/>
    <key>com.apple.private.security.container-required</key>
    <false/>
</dict>
</plist>
```
which was referenced in [theos/templates#11](https://github.com/theos/templates/issues/11)

**Comment by andermoran** [comment] 2019-08-13 16:50
Solution:
1. Create `ent.plist` file in project directory
2. Open the plist file and write
```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>platform-application</key>
    <true/>
    <key>com.apple.private.security.container-required</key>
    <false/>
</dict>
</plist>
```
3. Add `tweakname_CODESIGN_FLAGS = -Sent.plist` to Makefile
