### ISSUE TITLE
How to include 3rd Party Framework?

### ISSUE THREAD

**Issue by thiesdiggity** [theos/theos#124] opened 2015-11-29 23:43 UTC
Hi,

I have searched everywhere on how to compile a theos tweak with a 3rd party framework (AWS) but everything I try doesn't seem to work. Basically I would like to include the AWS Framework within my tweak.

I have the frameworks (AWS Core & AWS S3) in the ./External folder. When I try to compile the application it says:

    fatal error: 'AWSS3/AWSS3.h' file not found

In my Makefile I have the following:

    XXXXX_CFLAGS += -I./External/

What am I missing? I have been working on this for hours and I'm at a loss for what else to do to make this work. Any help would be greatly appreciated!

Thanks!

**Comment by gongting** [comment] 2016-01-11 10:27
Maybe this is helpful  :)
https://www.reddit.com/r/jailbreakdevelopers/comments/39i7uc/links_external_framework/

**Comment by alucard0134** [comment] 2016-02-13 17:19
@thiesdiggity Are you still experiencing this issue?

**Comment by kirb** [comment] 2016-02-13 22:40
This is probably a duplicate of #110. Be sure to read my comment there.
On Sun, 14 Feb 2016 at 03:49, alucard0134 <notifications@github.com> wrote:

> @thiesdiggity <https://github.com/thiesdiggity> Are you still
> experiencing this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theos/theos/issues/124#issuecomment-183706077>.
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by alucard0134** [comment] 2016-02-14 03:22
Based on creators inactivity and an answer being supplied I am going to close this issue, if you still have troubles feel free to comment back here

**Closed by alucard0134** 2016-02-14 03:22 UTC

**Comment by liuxuan30** [comment] 2017-06-27 08:33
Hello there, sorry to dig this out again.

I am trying to add S3 framework as well, here's my makefile:
```makefile
MyWorker_EXTRA_FRAMEWORKS = AWSCore AWSS3
MyWorker_FRAMEWORKS = UIKit Security CoreGraphics
```
and I put the two frameworks under:
```
xuan:myworker xuanliu$ ls theos/lib/
AWSCore.framework	AWSS3.framework

It can build, but when trying to run:
```
dyld: Library not loaded: @rpath/AWSCore.framework/AWSCore
  Referenced from: /usr/bin/MyWorker
  Reason: image not found
```

Can someone help?

**Comment by kirb** [comment] 2017-06-27 08:41
@liuxuan30, please refer to the [Help](https://github.com/theos/theos/wiki/Help) page; the Theos issue tracker isn't for getting help.

**Comment by liuxuan30** [comment] 2017-06-28 09:17
@kirb sorry about that. I have created https://stackoverflow.com/questions/44798352/framework-not-found-awscore-for-architecture-arm64-in-theos-makefile, not sure if you can get notice about it, but I am really confused and wonder if it's my project issue or theos issue. Please take a look and reply to that thread. Thanks again!

**Comment by kevinzheng** [comment] 2018-06-22 16:24
@liuxuan30 I met the same problem, have you got the solution？

**Comment by liuxuan30** [comment] 2018-06-25 00:58
I did. 
```
_CFLAGS = -I./AWS/include
_LDFLAGS = -L./AWS/lib -lsqlite3 -lz -lAWSCore -lAWSS3
```
and folder looks like
![image](https://user-images.githubusercontent.com/4375169/41825726-fa4542ac-7855-11e8-8f99-c0000a5686dc.png)

**Comment by kevinzheng** [comment] 2018-06-25 04:06
@liuxuan30 Thank you, but I need to use 3rd party frameworks such as `Fabric.framework`, not the static libraries.

**Comment by liuxuan30** [comment] 2018-07-11 02:02
It's the same. Just different types.
