### ISSUE TITLE
No compile errors when hooking not-existing method

### ISSUE THREAD

**Issue by julakali** [theos/theos#233] opened 2017-02-16 15:15 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. setup logos
2. create sample tweak
3. hook some non existant class-method like this:

```
%hook SpringBoard
	-(void) thisMethodDoesNotExistInHeaders:(id)arg {
		%orig(arg);
	}
%end
```

What happens?
-------------
make package compiles tweak just fine

What were you expecting to happen?
----------------------------------
compile error because method does not exist in header.

**Comment by rpetrich** [comment] 2017-02-16 15:31
It isn't possible to provide this warning without direct integration in the compiler. A lesser warning is available by enabling the "undeclared selector" compiler warnings.

**Comment by julakali** [comment] 2017-02-16 16:35
Thank you, that's helpful.
Wouldn't it be good to enable this warning by default?

**Comment by uroboro** [comment] 2017-02-17 04:29
Bear in mind that the existence of some methods and classes depends on the iOS version. You'd have to have headers with all of the declarations you will be hooking and lacking it would result in warnings or errors. As is, Logos provides a fast and simple hooking syntax.

**Comment by kirb** [comment] 2017-03-18 11:34
Closing as this is not a bug and probably not going to become a feature, and a clang-based solution was provided above.

**Closed by kirb** 2017-03-18 11:34 UTC
