### ISSUE TITLE
Can't compile for OS X

### ISSUE THREAD

**Issue by Cykey** [theos/theos#186] opened 2016-08-07 21:32 UTC
## What are the steps to reproduce this issue?
1. Create a new 'tool' project.
2. Add `export TARGET = native:clang:10.9` to your makefile.
3. Run `make`.
## What happens?

It compiles for ARM.
## What were you expecting to happen?

Compile for OS X.
## Any other comments?

If you add `export ARCHS = x86_64 i386`, it compiles with the iPhone SDK and you get thousands of header errors.
## What versions of software are you using?

**Operating System:** : 10.11

**Toolchain Version:** : Not sure. Probably latest from git.

**SDK Version:** : 10.11

**Comment by uroboro** [comment] 2016-08-07 23:59
Try using `simulator` as target platform. Toolchain should be the one from Xcode.

**Comment by DHowett** [comment] 2016-08-08 01:36
This report is regarding _building for OS X_, which is a capstone feature
in legacy Theos. Thus the native target.

**Comment by uroboro** [comment] 2016-08-08 05:02
I know, but the simulator target still builds binaries that run on OS X. Anyways, I have [this](https://github.com/uroboro/com) project that has `export TARGET = native:clang::latest` and builds both on iOS and OS X just fine.

**Comment by kirb** [comment] 2016-08-08 07:21
I can’t reproduce this issue:

```shellsession
$ cat Makefile
TARGET = native:clang:10.9

include $(THEOS)/makefiles/common.mk

TOOL_NAME = f
f_FILES = main.mm

include $(THEOS_MAKE_PATH)/tool.mk

$ make do
> Making all for tool f…
==> Compiling main.mm (i386)…
==> Linking tool f (i386)…
==> Compiling main.mm (x86_64)…
==> Linking tool f (x86_64)…
==> Merging tool f…
> Making stage for tool f…
pkgbuild: Inferring bundle components from contents of /tmp/f/.theos/_
pkgbuild: Wrote package to ./packages/ws.hbang.f_0.0.1-3+debug.pkg
==> Installing…
su: illegal option -- c
usage: su [-] [-flm] [login [args]]
make: *** [/Users/kirb/theos/makefiles/install/pkg_local.mk:2: internal-install] Error 1
```

(Apparently install.exec is broken though… will fix)

You did place your `TARGET` line before `common.mk` is included? It won’t be taken into account afterwards.

@uroboro, nowadays simulator dyld expects a load command that marks the binary as specifically for iOS simulator (or watch, or TV). Unsure if OS X/iOS dyld care about them, though.

**Comment by Cykey** [comment] 2016-08-08 14:22
Still can't get it to work. 
Here's my makefile:
```
davidsmbp:a cykey$ cat Makefile
export TARGET = native:clang:10.9:10.9

include $(THEOS)/makefiles/common.mk

TOOL_NAME = a
a_FILES = main.mm

include $(THEOS_MAKE_PATH)/tool.mk
davidsmbp:a cykey$
```

**Comment by uroboro** [comment] 2016-08-08 14:32
Attach the link from `make troubleshoot` after making sure Theos is up to date please.

**Comment by Cykey** [comment] 2016-08-08 15:16
Theos is up to date.
https://ghostbin.com/paste/kn6qo

**Comment by mstg** [comment] 2016-08-17 13:20
I can't reproduce this issue either.

```
λ mustafa [jb/test/native_test] → cat Makefile
export TARGET = native:clang

include $(THEOS)/makefiles/common.mk

TOOL_NAME = native_test
native_test_FILES = main.mm
native_test_INSTALL_PATH = /usr/local/bin

include $(THEOS_MAKE_PATH)/tool.mk

λ mustafa [jb/test/native_test] → make
> Making all for tool native_test…
==> Compiling main.mm (i386)…
==> Linking tool native_test (i386)…
==> Compiling main.mm (x86_64)…
==> Linking tool native_test (x86_64)…
==> Merging tool native_test…
```

@Cykey Can you try defining `SYSROOT`?
Like this: `export SYSROOT = /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`

**Comment by Cykey** [comment] 2016-08-17 22:33
Does not work either.

**Comment by DHowett** [comment] 2016-08-17 22:35
The output from `make all mesasges=yes` may be helpful in diagnosing this.

**Comment by Cykey** [comment] 2016-08-17 22:51
https://ghostbin.com/paste/ajvz3

**Comment by kirb** [comment] 2017-03-19 03:40
The Darwin/macosx target is pretty out of date compared to the others, and I’ve noticed a few other issues as well (but still not this particular one unfortunately). So I reckon #242 is likely to fix this, assuming Darwin/iphone works fine on the same machine. Closing in favor of that issue. (If it doesn’t fix it, reopen this or file a new issue.)

**Closed by kirb** 2017-03-19 03:40 UTC
Labels: Component: Makefiles, Platform:OSX
