### ISSUE TITLE
Cant Build Swift App

### ISSUE THREAD

**Issue by amirhacks** [theos/theos#564] opened 2020-12-31 03:32 UTC
(Thanks for reporting an issue! Please makeup  sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
… I GET THIS ERROR WHEN I BUILD SWIFT APP USING THEOS 
> Making all for application app…
==> Copying resource directories into the application wrapper…
==> Compiling AppDelegate.swift (arm64)…
<unknown>:0: error: invalid value '5' in '-swift-version 5'
<unknown>:0: note: valid arguments to '-swift-version' are '3', '4'
Assertion failed: (!plural.empty()), function getCommonPluralPrefix, file /Users/kabiroberai/Desktop/Xcode/swift-source/swift/lib/ClangImporter/ImportEnumInfo.cpp, line 159.
0  swift                    0x00000001035b2f10 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 60
1  swift                    0x00000001035b3628 SignalHandler(int) + 652
2  libsystem_platform.dylib 0x000000019e2fa9ec <redacted> + 40
3  libsystem_pthread.dylib  0x000000019e300094 <redacted> + 380
4  libsystem_c.dylib        0x000000019e1dfea8 abort + 140
5  libsystem_c.dylib        0x000000019e1adb58 basename_r + 0
6  swift                    0x0000000101446618 swift::importer::EnumInfo::determineConstantNamePrefix(swift::ASTContext&, clang::EnumDecl const*) + 0
7  swift                    0x00000001014469bc swift::importer::EnumInfo::determineConstantNamePrefix(swift::ASTContext&, clang::EnumDecl const*) + 932
8  swift                    0x0000000101446d84 swift::importer::EnumInfoCache::getEnumInfo(clang::EnumDecl const*) + 344
9  swift                    0x000000010144c2a8 swift::importer::NameImporter::determineEffectiveContext(clang::NamedDecl const*, clang::DeclContext const*, swift::importer::ImportNameVersion) + 80
10 swift                    0x000000010144d284 swift::importer::NameImporter::importNameImpl(clang::NamedDecl const*, swift::importer::ImportNameVersion, clang::DeclarationName) + 172
11 swift                    0x000000010144f9c0 swift::importer::NameImporter::importName(clang::NamedDecl const*, swift::importer::ImportNameVersion, clang::DeclarationName) + 320
12 swift                    0x000000010146047c swift::importer::addEntryToLookupTable(swift::SwiftLookupTable&, clang::NamedDecl*, swift::importer::NameImporter&) + 128
13 swift                    0x0000000101460650 swift::importer::addEntryToLookupTable(swift::SwiftLookupTable&, clang::NamedDecl*, swift::importer::NameImporter&) + 596
14 swift                    0x000000010145d8dc swift::SwiftLookupTableWriter::writeExtensionContents(clang::Sema&, llvm::BitstreamWriter&) + 352
15 swift                    0x0000000102bd5f40 clang::ASTWriter::WriteModuleFileExtension(clang::Sema&, clang::ModuleFileExtensionWriter&) + 1072
16 swift                    0x0000000102bdeafc clang::ASTWriter::WriteASTCore(clang::Sema&, llvm::StringRef, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*) + 12420
17 swift                    0x0000000102bdb9a4 clang::ASTWriter::WriteAST(clang::Sema&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*, llvm::StringRef, bool) + 724
18 swift                    0x0000000102c1bf9c clang::PCHGenerator::HandleTranslationUnit(clang::ASTContext&) + 224
19 swift                    0x00000001029f34a0 clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 52
20 swift                    0x0000000102c267dc clang::ParseAST(clang::Sema&, bool, bool) + 444
21 swift                    0x00000001029cfba4 clang::FrontendAction::Execute() + 88
22 swift                    0x000000010299ff5c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1144
23 swift                    0x0000000103550bcc llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 224
24 swift                    0x0000000103550d78 RunSafelyOnThread_Dispatch(void*) + 52
25 swift                    0x00000001035b46f0 ExecuteOnThread_Dispatch(void*) + 16
26 libsystem_pthread.dylib  0x000000019e3092c0 <redacted> + 128
27 libsystem_pthread.dylib  0x000000019e309220 _pthread_start + 44
28 libsystem_pthread.dylib  0x000000019e30ccdc thread_start + 4
Stack dump:
0.      <eof> parser at end of file
bash: line 1:  1520 Abort trap: 6           ( swift -frontend -c -I/var/theos/include -I/var/theos/vendor/include -I/var/theos/include/_fallback -emit-dependencies-path "/var/mobile/Downloads/app/.theos/obj/debug/arm64/AppDelegate.swift.6dd23d1d.Td" -color-diagnostics -DTHEOS_SWIFT -DTARGET_IPHONE -module-name app -g -swift-version 5 -sdk "/var/theos/sdks/iPhoneOS13.5.sdk" -DDEBUG -Onone -target arm64-apple-ios7.0 -emit-module-path /var/mobile/Downloads/app/.theos/obj/debug/arm64/AppDelegate.swift.6dd23d1d.swiftmodule -primary-file AppDelegate.swift RootViewController.swift -o /var/mobile/Downloads/app/.theos/obj/debug/arm64/AppDelegate.swift.6dd23d1d.o )
make[3]: *** [/var/theos/makefiles/instance/rules.mk:250: /var/mobile/Downloads/app/.theos/obj/debug/arm64/AppDelegate.swift.6dd23d1d.o] Error 134
==> Compiling AppDelegate.swift (armv7)…
<unknown>:0: error: invalid value '5' in '-swift-version 5'
<unknown>:0: note: valid arguments to '-swift-version' are '3', '4'
Assertion failed: (!plural.empty()), function getCommonPluralPrefix, file /Users/kabiroberai/Desktop/Xcode/swift-source/swift/lib/ClangImporter/ImportEnumInfo.cpp, line 159.
0  swift                    0x000000010344af10 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 60
1  swift                    0x000000010344b628 SignalHandler(int) + 652
2  libsystem_platform.dylib 0x000000019e2fa9ec <redacted> + 40
3  libsystem_pthread.dylib  0x000000019e300094 <redacted> + 380
4  libsystem_c.dylib        0x000000019e1dfea8 abort + 140
5  libsystem_c.dylib        0x000000019e1adb58 basename_r + 0
6  swift                    0x00000001012de618 swift::importer::EnumInfo::determineConstantNamePrefix(swift::ASTContext&, clang::EnumDecl const*) + 0
7  swift                    0x00000001012de9bc swift::importer::EnumInfo::determineConstantNamePrefix(swift::ASTContext&, clang::EnumDecl const*) + 932
8  swift                    0x00000001012ded84 swift::importer::EnumInfoCache::getEnumInfo(clang::EnumDecl const*) + 344
9  swift                    0x00000001012e42a8 swift::importer::NameImporter::determineEffectiveContext(clang::NamedDecl const*, clang::DeclContext const*, swift::importer::ImportNameVersion) + 80
10 swift                    0x00000001012e5284 swift::importer::NameImporter::importNameImpl(clang::NamedDecl const*, swift::importer::ImportNameVersion, clang::DeclarationName) + 172
11 swift                    0x00000001012e79c0 swift::importer::NameImporter::importName(clang::NamedDecl const*, swift::importer::ImportNameVersion, clang::DeclarationName) + 320
12 swift                    0x00000001012f847c swift::importer::addEntryToLookupTable(swift::SwiftLookupTable&, clang::NamedDecl*, swift::importer::NameImporter&) + 128
13 swift                    0x00000001012f8650 swift::importer::addEntryToLookupTable(swift::SwiftLookupTable&, clang::NamedDecl*, swift::importer::NameImporter&) + 596
14 swift                    0x00000001012f58dc swift::SwiftLookupTableWriter::writeExtensionContents(clang::Sema&, llvm::BitstreamWriter&) + 352
15 swift                    0x0000000102a6df40 clang::ASTWriter::WriteModuleFileExtension(clang::Sema&, clang::ModuleFileExtensionWriter&) + 1072
16 swift                    0x0000000102a76afc clang::ASTWriter::WriteASTCore(clang::Sema&, llvm::StringRef, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*) + 12420
17 swift                    0x0000000102a739a4 clang::ASTWriter::WriteAST(clang::Sema&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, clang::Module*, llvm::StringRef, bool) + 724
18 swift                    0x0000000102ab3f9c clang::PCHGenerator::HandleTranslationUnit(clang::ASTContext&) + 224
19 swift                    0x000000010288b4a0 clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 52
20 swift                    0x0000000102abe7dc clang::ParseAST(clang::Sema&, bool, bool) + 444
21 swift                    0x0000000102867ba4 clang::FrontendAction::Execute() + 88
22 swift                    0x0000000102837f5c clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1144
23 swift                    0x00000001033e8bcc llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 224
24 swift                    0x00000001033e8d78 RunSafelyOnThread_Dispatch(void*) + 52
25 swift                    0x000000010344c6f0 ExecuteOnThread_Dispatch(void*) + 16
26 libsystem_pthread.dylib  0x000000019e3092c0 <redacted> + 128
27 libsystem_pthread.dylib  0x000000019e309220 _pthread_start + 44
28 libsystem_pthread.dylib  0x000000019e30ccdc thread_start + 4
Stack dump:
0.      <eof> parser at end of file
bash: line 1:  1522 Abort trap: 6           ( swift -frontend -c -I/var/theos/include -I/var/theos/vendor/include -I/var/theos/include/_fallback -emit-dependencies-path "/var/mobile/Downloads/app/.theos/obj/debug/armv7/AppDelegate.swift.4599414b.Td" -color-diagnostics -DTHEOS_SWIFT -DTARGET_IPHONE -module-name app -g -swift-version 5 -sdk "/var/theos/sdks/iPhoneOS13.5.sdk" -DDEBUG -Onone -target armv7-apple-ios7.0 -emit-module-path /var/mobile/Downloads/app/.theos/obj/debug/armv7/AppDelegate.swift.4599414b.swiftmodule -primary-file AppDelegate.swift RootViewController.swift -o /var/mobile/Downloads/app/.theos/obj/debug/armv7/AppDelegate.swift.4599414b.o )
make[3]: *** [/var/theos/makefiles/instance/rules.mk:250: /var/mobile/Downloads/app/.theos/obj/debug/armv7/AppDelegate.swift.4599414b.o] Error 134
make[2]: *** [/var/theos/makefiles/instance/application.mk:50: /var/mobile/Downloads/app/.theos/obj/debug/arm64/app.app/app] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [/var/theos/makefiles/instance/application.mk:50: /var/mobile/Downloads/app/.theos/obj/debug/armv7/app.app/app] Error 2
make[1]: *** [/var/theos/makefiles/instance/application.mk:41: internal-application-all_] Error 2
make: *** [/var/theos/makefiles/master/rules.mk:116: app.all.application.variables] Error 2
ssh:/var/mobile/Downloads/app root# 

What versions of software are you using?
----------------------------------------
**Operating System:** … IOS

**Toolchain Version:** …

**SDK Version:** …13.5

**Comment by kabiroberai** [comment] 2020-12-31 11:02
This is a duplicate of #547; closing in favor of that.

**Closed by kabiroberai** 2020-12-31 11:02 UTC
