### ISSUE TITLE
Compiling an aggergated project with Procursus-bootstrapped macOS results in "Bad file descriptor" spam

### ISSUE THREAD

**Issue by Absolucy** [theos/theos#589] opened 2021-04-30 13:49 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. Bootstrap macOS using Procursus
2. Create a Theos project
3. Create a Theos subproject (in a way where Theos will automatically insert the `subprojects` stuff in the makefile)
4. Run any make command - `make clean` will even suffice (doesn't matter if it's normal macOS `make` or Procursus' `gmake`, same result)

What happens?
-------------
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: Bad file descriptor` will be spammed.
Nothing seems to be impacted, everything compiles fine, but you have to scroll through the spam to find any actual errors, and it's just an eyesore in general.

What were you expecting to happen?
----------------------------------
No spam.

Any logs, error output, etc?
----------------------------
https://ghostbin.co/paste/v3uxucs

Any other comments?
-------------------
This isn't related to my shell environment - renaming zshrc/bashrc/profile so that they don't load will still result in the same thing.

This also doesn't happen if there's no subprojects.

Theos is on the latest commit of the `kabiroberai/orion` branch (https://github.com/theos/theos/commit/129dc64).

What versions of software are you using?
----------------------------------------
**Operating System:** macOS 11.3 (also happened with 11.2)

**Toolchain Version:** Xcode 12.5 (also happened with older 12.x versions)

**SDK Version:** iOS 14.4 (from https://github.com/theos/sdks)

**Comment by kabiroberai** [comment] 2021-05-01 01:34
Does this happen on master as well?

**Comment by aspenluxxxy** [comment] 2021-05-01 01:38
Yes.

**Comment by kabiroberai** [comment] 2021-05-27 13:26
I haven't had time to track down the root cause yet, but it's worth mentioning that this occasionally happens when using Theos with GitHub Actions as well

**Comment by kirb** [comment] 2022-01-15 04:44
@Absolucy Could you confirm if this is fixed?

**Comment by opa334** [comment] 2022-09-17 17:22
@kirb does not seem to be fixed :/

**Comment by opa334** [comment] 2022-09-17 19:16
seems to only happen when I have a subproject in my theos project

**Comment by kirb** [comment] 2022-09-18 00:31
Yeah this should be reopened, but I don’t think we can fix this. It’s just something to do with Procursus’ bash and/or make.

**Comment by opa334** [comment] 2022-09-18 11:19
It's definitely not Procursus bash/zsh or make because this happens even when I'm using Xcode make and stock zsh.

This happens as soon as procursus is in the path.

**Comment by opa334** [comment] 2022-09-18 12:38
If I remove /opt/procursus/bin/bash, the spam stops, maybe this is helpful to fix it

**Comment by opa334** [comment] 2022-09-19 15:45
This turned out to be a problem with procursus bash, will be fixed soon, this issue can be closed now @kirb

**Comment by kirb** [comment] 2022-10-30 04:18
Closing since it's been fixed in Procursus now, thanks @opa334 and @TheRealKeto for figuring it out.

**Closed by kirb** 2022-10-30 04:18 UTC
