### ISSUE TITLE
Theos error: Can't call method "isNew" on an undefined value at /var/mobile/sbtest1/theos/bin/logos.pl line 382

### ISSUE THREAD

**Issue by roboduino** [theos/theos#133] opened 2016-02-21 04:16 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Create your tweak 
2. Use "make package install" in the directory
3. Get this error

What happens?
-------------
The tweak does not compile and the error prevents you from doing anything with your code without getting an error

What were you expecting to happen?
----------------------------------
My tweak would compile and I would get an alert when SpringBoard loads

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
WillPhone:/var/mobile/sbtest1 root# make package install
/var/mobile/sbtest1/theos/makefiles/targets/Darwin-arm/iphone.mk:43: Targeting iOS 4.0 and higher is not supported with iphone-gcc. Forcing clang.
Making all for tweak sbtest1...
 Preprocessing Tweak.xm...
Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.
Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.
Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.
Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.
Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.
Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.
Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.
Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.
Can't call method "isNew" on an undefined value at /var/mobile/sbtest1/theos/bin/logos.pl line 382.
make[2]: *** [obj/Tweak.xm.a114fd55.o] Error 255
make[1]: *** [internal-library-all_] Error 2
make: *** [sbtest1.all.tweak.variables] Error 2
WillPhone:/var/mobile/sbtest1 root# 

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** iOS 8.3

**Toolchain Version:** 6.1-1

**SDK Version:** iOS 8.1

**Comment by uroboro** [comment] 2016-02-21 04:50
> Constants from lexical variables potentially modified elsewhere are deprecated at /private/var/theos/bin/lib/aliased.pm line 42.

Comes from using perl 5.21.7 or newer. A patch is in the works.

> Can't call method "isNew" on an undefined value at /var/mobile/sbtest1/theos/bin/logos.pl line 382.

[logos.pl#L382](https://github.com/theos/theos/blob/master/bin%2Flogos.pl#L382) contains the following line
``` perl
		} elsif($line =~ /\G%orig\b/gc) {
```
which makes me doubt you are using an up to date version of Theos. Please correct me if I'm wrong.

**Comment by DHowett** [comment] 2016-02-21 09:19
This could be caused by using %orig outside a hook.

**Comment by kirb** [comment] 2016-07-16 11:28
Closing this as the reporter did not respond. If you are still having problems, reopen this and make a comment.

**Closed by kirb** 2016-07-16 11:28 UTC
Labels: Component: Logos, Fix
